import Image from "next/image";
import Link from "next/link";
import { CTA } from "./components/CTA";
import { PageShell } from "./components/PageShell";
import { capabilities, products, sports } from "./components/site-data";

export default function Home() {
  return <PageShell>
    <section className="hero">
      <div className="hero-glow hero-glow-one"/><div className="hero-glow hero-glow-two"/>
      <div className="hero-content"><p className="eyebrow">The connected sports analysis platform</p><h1>Analyse the game.<span>Deliver the insight.</span></h1><p className="hero-copy">FAST brings live coding, post-match review and cloud delivery into one focused multi-sport workflow.</p><div className="hero-actions"><Link className="button button-primary" href="/trial">Start your trial <span>↗</span></Link><Link className="button button-quiet" href="/platform">Explore the platform <span>↓</span></Link></div><div className="hero-proof"><div><strong>10</strong><span>sports supported</span></div><div><strong>5</strong><span>connected products</span></div><div><strong>1</strong><span>unified workflow</span></div></div></div>
      <div className="hero-product" aria-label="FAST platform overview"><div className="window-bar"><span/><span/><span/><p>FAST Sports Analytics</p></div><div className="product-screen"><aside><Image src="/branding/fast-logo.png" alt="" width={210} height={72}/><div className="side-nav"><span className="active">Overview</span><span>Matches</span><span>Analysis</span><span>Viewer</span><span>Organisation</span></div></aside><div className="dashboard"><div className="dashboard-heading"><div><small>Match workspace</small><h2>Performance overview</h2></div><span className="live-pill">Live</span></div><div className="metric-grid"><article><small>Possession</small><strong>58%</strong><i style={{width:"58%"}}/></article><article><small>Final third entries</small><strong>31</strong><i style={{width:"72%"}}/></article><article><small>Shots</small><strong>14</strong><i style={{width:"64%"}}/></article></div><div className="timeline-card"><div className="timeline-header"><span>Match timeline</span><small>Second half</small></div><div className="timeline"><span className="event e1"/><span className="event e2"/><span className="event e3"/><span className="event e4"/><span className="event e5"/></div><div className="clip-list"><span><b>62:14</b>High regain</span><span><b>68:40</b>Final-third entry</span><span><b>74:09</b>Shot on target</span></div></div></div></div></div>
    </section>
    <section className="trust-strip"><span>LIVE ANALYSIS</span><i/><span>POST-MATCH REVIEW</span><i/><span>CLOUD DELIVERY</span><i/><span>MULTI-SPORT</span></section>
    <section className="content-section"><div className="section-heading"><p className="eyebrow">One platform. Every stage.</p><h2>From the first tag to the final conversation.</h2><p>Each FAST product has a clear purpose. Together they create a connected environment for analysis, review, administration, scouting and future assisted intelligence.</p></div><div className="product-list">{products.map(product => <Link className="product-card" href={`/platform/${product.slug}`} key={product.name}><div className="product-card-top"><span>{product.number}</span><small>{product.status}</small></div><h3>{product.name}</h3><p>{product.summary}</p><ul>{product.features.slice(0,3).map(feature => <li key={feature}>{feature}</li>)}</ul><div className="card-arrow">↗</div></Link>)}</div></section>
    <section className="content-section capabilities"><div className="capability-intro"><p className="eyebrow">Built around real analysis</p><h2>Less friction. More useful insight.</h2><p>FAST is designed around matchday, video review and communication—not a generic data dashboard.</p></div><div className="capability-grid">{capabilities.slice(0,4).map(([title,text], index) => <article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="content-section proof-section"><div className="section-heading compact"><p className="eyebrow">Built from the workflow</p><h2>Designed around what happens before, during and after the match.</h2><p>FAST connects the operational details that normally sit across separate tools, folders and conversations.</p></div><div className="proof-grid"><article><span>01</span><h3>Match-ready setup</h3><p>Sport, squad, formation, coding template and user access stay connected from the start.</p></article><article><span>02</span><h3>Live decision support</h3><p>Capture events, create clips and deliver relevant moments while the match is still moving.</p></article><article><span>03</span><h3>Structured review</h3><p>Return to searchable events, player context, playlists and comments without rebuilding the analysis.</p></article><article><span>04</span><h3>Controlled delivery</h3><p>Use roles, licences and cloud access to put the right content in front of the right people.</p></article></div></section>
    <section className="content-section sports-preview"><div><p className="eyebrow">Multi-sport by design</p><h2>One platform. Your sport.</h2><p>Sport-specific logic sits on top of a shared FAST workflow, giving every team the right match structure without fragmenting the platform.</p><Link className="inline-link" href="/sports">Explore all sports <span>→</span></Link></div><div className="sports-grid">{sports.map((sport,index)=><Link href={`/sports/${sport.slug}`} key={sport.slug}><span>{String(index+1).padStart(2,"0")}</span><strong>{sport.name}</strong></Link>)}</div></section>
    <section className="content-section beta-section"><div className="beta-panel"><div><p className="eyebrow">Private beta</p><h2>Built in real workflows. Refined with real users.</h2><p>FAST is currently onboarding selected analysts, coaches and performance teams while the connected platform is prepared for wider release.</p></div><div className="beta-points"><span><b>01</b>Guided onboarding</span><span><b>02</b>Controlled releases</span><span><b>03</b>Direct product feedback</span><span><b>04</b>Organisation-ready access</span></div><Link className="button button-primary" href="/trial">Request early access <span>↗</span></Link></div></section>
    <CTA />
  </PageShell>;
}
