import Link from "next/link";
import { PageShell } from "../components/PageShell";

const downloads=[
{name:"FAST Launcher",status:"Private beta",text:"Sign in, verify your licence, check for updates and open the FAST products available to your account."},
{name:"FAST Analysis",status:"Private beta",text:"Desktop match coding and performance analysis for modern Windows environments."},
{name:"FAST Viewer",status:"Private beta",text:"Focused clip review, playlists, comments and telestration for coaches."},
{name:"FAST Scout",status:"In development",text:"Structured observations, player reports and connected recruitment workflows."}
];
const requirements=[["Operating system","Windows 11 recommended"],["Memory","16 GB minimum · 32 GB recommended"],["Graphics","Modern dedicated GPU recommended for video workflows"],["Connection","Internet access required for sign-in, licences and cloud delivery"]];
export default function Downloads(){return <PageShell><section className="page-hero"><p className="eyebrow">Downloads</p><h1>Your FAST workspace.<br/><span>Ready when your account is.</span></h1><p className="lead">Public downloads are not yet available. Early-access users receive approved releases through FAST Launcher and their licensed account.</p></section><section className="content-section"><div className="download-list">{downloads.map((item,index)=><article key={item.name}><span>{String(index+1).padStart(2,"0")}</span><div><small>{item.status}</small><h2>{item.name}</h2><p>{item.text}</p></div><button disabled>Account required</button></article>)}</div><div className="info-panel"><div><p className="eyebrow">Release model</p><h2>Controlled, account-based delivery</h2></div><p>FAST Launcher manages authenticated access, permitted products and approved updates. Users only see applications included in their organisation role and licence.</p><Link className="inline-link" href="/docs">Read documentation <span>→</span></Link></div></section><section className="content-section soft-section"><div className="section-heading compact"><p className="eyebrow">Windows requirements</p><h2>Prepared for professional video workflows.</h2><p>Final supported specifications will be confirmed before public launch. The current private-beta baseline is shown below.</p></div><div className="requirements-grid">{requirements.map(([label,value])=><article key={label}><small>{label}</small><strong>{value}</strong></article>)}</div><div className="release-flow"><span>01<strong>Sign in</strong></span><i>→</i><span>02<strong>Verify access</strong></span><i>→</i><span>03<strong>Install</strong></span><i>→</i><span>04<strong>Stay updated</strong></span></div></section></PageShell>}
